### ISSUE TITLE
nice work but...

### ISSUE THREAD

**Issue by RonXTCdaBass** [arabacibahadir/pokitch#23]
how to change the commands?
it disturbs with PCG

and
where is a complete list with all commands?

**Comment by arabacibahadir** [comment]
Hi,
You can see commands at [https://pokitch.app](https://pokitch.app). Right now we have only three commands that you can use. !poke welcomepack, !poke attack and !poke inventory. If you have any suggestion about new commands, please open new issue for new feature request. 
Thanks!
