### ISSUE TITLE
add Prettier

### ISSUE THREAD

**Issue by mertsabinov** [arabacibahadir/pokitch#37]

**Comment by arabacibahadir** [comment]
Currently we already have it. Is there a prettier unimplemented project file that we have overlooked? Prettier'ed all the files again, I didn't see an error.
https://github.com/arabacibahadir/pokitch/blob/53612126516aa97eb9e4c23e6872d3564fe40a15/package.json#L35

**Comment by mertsabinov** [comment]
> Currently we already have it. Is there a prettier unimplemented project file that we have overlooked? Prettier'ed all the files again, I didn't see an error.
> 
> https://github.com/arabacibahadir/pokitch/blob/53612126516aa97eb9e4c23e6872d3564fe40a15/package.json#L35

hi,
If we create a .prettierrc file within a project, it will have a common configuration for everyone. For example, a sample .prettierrc file could contain the following settings

```json
{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
  "arrowParens": "avoid"
}
```

**Comment by arabacibahadir** [comment]
@mertsabinov Thanks for the contribution!
