### ISSUE TITLE
shorten chat commands

### ISSUE THREAD

**Issue by arabacibahadir** [arabacibahadir/pokitch#50]
we can shorten the codes in twitch chat like instead of :
"!poke attack" => "!poke a"
"!poke welcomepack" => "!poke wp"

**Comment by Subham5401** [comment]
Hi, I'd like to take this further.

**Comment by Subham5401** [comment]
Could you provide more details about the issue? As far as I understand, there is a need to replace "!poke attack" in the description with "!poke a" on the FeaturesHomePage. Can you please confirm if my understanding is correct?

**Comment by arabacibahadir** [comment]
Hello, thanks for the contribution!
We need to add shorter versions of chat commands also we want to keep both functions such as "!poke attack" and "!poke a".
In the `./src/pages/overlays/[id].tsx` https://github.com/arabacibahadir/pokitch/blob/5d63bbeda19a9f22a5b0ce470eacdee08b4d9651/src/pages/overlays/%5Bid%5D.tsx#L45
Lines between 45-50 should change like this:

```javascript
        if (cmd === "welcomepack" || cmd === "wp") {
          return await poke.welcomePack(tmiClient, userName, channelName);
        } else if (cmd === "attack" || cmd === "a") {
          return await poke.attack(tmiClient, userName, channelName);
        } else if (cmd === "inventory" || cmd === "i") {
          return await poke.inventory(tmiClient, userName, channelName);
```

**Comment by Subham5401** [comment]
Thank you for the explanation @arabacibahadir
