### ISSUE TITLE
fix: mention user by the bot

### ISSUE THREAD

**Issue by emredevsalot** [arabacibahadir/pokitch#52]
![image](https://user-images.githubusercontent.com/72770244/235304852-335e87ee-6cf0-4110-95f0-0a2d1b407a20.png)

Since the bot mentions the user like the last character of the user's name is a .(dot), it can't mention users properly.(Unable to fetch)

Extra: I don't think we need the "@" sign as well, after the latest updates at Twitch, where you can mention users with or without the "@" sign.

**Comment by arabacibahadir** [comment]
Hello, thanks for the contribution!
Nice catch, I think we should still keep "@" sign for better user highlight in text.
